// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using events_service.Infrastructure.Persistence;

#nullable disable

namespace eventsservice.Infrastructure.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20251129180138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("events_service.Infrastructure.Persistence.EventoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_horas");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizador_id");

                    b.Property<decimal>("TarifaPublicacion")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tarifa_publicacion");

                    b.Property<Guid?>("TransaccionPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaccion_pago_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("events_service.Infrastructure.Persistence.SeccionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioMonto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_monto");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("secciones", (string)null);
                });

            modelBuilder.Entity("events_service.Infrastructure.Persistence.SeccionEntity", b =>
                {
                    b.HasOne("events_service.Infrastructure.Persistence.EventoEntity", "Evento")
                        .WithMany("Secciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("events_service.Infrastructure.Persistence.EventoEntity", b =>
                {
                    b.Navigation("Secciones");
                });
#pragma warning restore 612, 618
        }
    }
}
